In [1]:
import numpy as np

In [ ]:
np.set_printoptions(suppress=True) # to suppress scientific notation in numpy array output

In [12]:
scalar = 5
print(scalar)
print("type of scalar:", type(scalar))
print("shape of scalar:", scalar.shape if hasattr(scalar, 'shape') else "N/A")
print("---"*20)

vector = np.array([1,2,3])
print(vector)
print("type of vector:", type(vector))
print("shape of vector:", vector.shape)
print("---"*20)

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print("type of matrix:", type(matrix))
print("shape of matrix:", matrix.shape)
print("---"*20)

tensor = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(tensor)
print("type of tensor:", type(tensor))
print("shape of tensor:", tensor.shape)

5
type of scalar: <class 'int'>
shape of scalar: N/A
------------------------------------------------------------
[1 2 3]
type of vector: <class 'numpy.ndarray'>
shape of vector: (3,)
------------------------------------------------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
type of matrix: <class 'numpy.ndarray'>
shape of matrix: (3, 3)
------------------------------------------------------------
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
type of tensor: <class 'numpy.ndarray'>
shape of tensor: (1, 3, 3)
