In [1]:
import numpy as np

In [ ]:
np.set_printoptions(suppress=True) # to suppress scientific notation in numpy array output

In [12]:
scalar = 5
print(scalar)
print("type of scalar:", type(scalar))
print("shape of scalar:", scalar.shape if hasattr(scalar, 'shape') else "N/A")
print("---"*20)

vector = np.array([1,2,3])
print(vector)
print("type of vector:", type(vector))
print("shape of vector:", vector.shape)
print("---"*20)

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print("type of matrix:", type(matrix))
print("shape of matrix:", matrix.shape)
print("---"*20)

tensor = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(tensor)
print("type of tensor:", type(tensor))
print("shape of tensor:", tensor.shape)

5
type of scalar: <class 'int'>
shape of scalar: N/A
------------------------------------------------------------
[1 2 3]
type of vector: <class 'numpy.ndarray'>
shape of vector: (3,)
------------------------------------------------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
type of matrix: <class 'numpy.ndarray'>
shape of matrix: (3, 3)
------------------------------------------------------------
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
type of tensor: <class 'numpy.ndarray'>
shape of tensor: (1, 3, 3)


Creating Vector and matrix for ml style Data

In [13]:
# Imagine we have 3 samples and 2 features
# Feature 1: hours studied
# Feature 2: number of practice questions
# target: pass (1)/ fail (0)

X = np.array([[2,30],[5,60],[3,40]]) # shape (3,2)

y = np.array([0,1,0]) # shape (3,)

print("Input Data matrix X:\n", X)
print("X shape:", X.shape)  # (n_samples, n_features)

print("Output Vector y:\n", y)
print("y shape:", y.shape)  # (n_samples,)

x1 = X[1]
print("First sample (x1):", x1)
print("Shape of x1:", x1.shape)  # (2,)

Input Data matrix X:
 [[ 2 30]
 [ 5 60]
 [ 3 40]]
X shape: (3, 2)
Output Vector y:
 [0 1 0]
y shape: (3,)
First sample (x1): [ 5 60]
Shape of x1: (2,)
